# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-19 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sucursal',
            name='diasPruebas',
            field=models.IntegerField(default=0, verbose_name='Dias de pruebas'),
        ),
    ]
