# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-07-19 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('FitApp', '0003_auto_20190719_1541'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscripcionFree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaSubscripcion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Subscripcion')),
                ('fechaFin', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Fin')),
                ('direccion', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('activa', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitApp.Cliente')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FitApp.Sucursal')),
            ],
        ),
    ]
