# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-08-13 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FitApp', '0004_subscripcionfree'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscripcionfree',
            name='sesiones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscripcionfree',
            name='sesionesRestantes',
            field=models.IntegerField(default=0),
        ),
    ]
