from django.conf.urls import include, url
from django.contrib import admin
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.http import HttpResponse
from .views import CustomerConektaApiView, BorrarCustomerConektaApiView, AddMetodoPagoApiView, deleteMetodoPagoApiView, MetodosPagoApiView, CalcularPromedioEvaluacionesAPIView, ConsultaFechaAPIView, SubscripcionMensualApiView, CancelarSubscripcionMensualApiView, ActualizarSubscripcionMensualApiView, CobrarPorSesionApiView, PerfilSucursalAPIView, DiasDisponiblesAPIView, ReportePagosSucursal

urlpatterns = [
    url(r'^$', views.Index),
    url(r'^Legal/$', views.Legal),
    url(r'^Avisos-Privacidad/$', views.Avisos),
    url(r'^QR/$', views.VistaQR),
    url(r'^Legal/usuarios/$', views.LegalDos),
    url(r'^Actividades/$', views.Actividades),
    url(r'^Paquetes/$', views.Paquetes),
    url(r'^Clubes/$', views.Clubes),
    url(r'^Clubes/(?P<sucursal_id>[0-9]+)/$',views.detalleSucursal),
    url(r'^index/$', views.IndexUsers),
    url(r'^BuscadorClub/$', views.BuscadorClub),
    url(r'^correoContacto/$', views.correoContacto),
    url(r'^getCiudadesWeb/(?P<estado_id>\d+)/$', views.getCiudadesWeb),
    url(r'^Contratar-plan-mensual/(?P<sucursal_id>[0-9]+)/$',views.paquetesPagoMensual),
    url(r'^Contratar-plan-diario/(?P<sucursal_id>[0-9]+)/$',views.paquetesPagoDiario),
    url(r'^Contratar-plan-free/(?P<sucursal_id>[0-9]+)/$',views.paquetesPagoFree),
    url(r'^PagoMensualplan/$', views.PagoMensualplan),
    url(r'^PagoDiarioplan/$', views.PagoDiarioplan),
    url(r'^PagPlanFree/$', views.PagPlanFree),
    url(r'^Iniciar-Sesion/$', views.LoginClientes),
    url(r'^Registrarse/$', views.RegitrarseClinete),
    url(r'^codigoVerificacion/$', views.codigoVerificacion),
    url(r'^verificacion/$', views.verificacion),
    url(r'^usuarioTelefono/$', views.usuarioTelefono),
    url(r'^RegistroCliente/$', views.RegistroCliente),
    url(r'^PerfilUsuario/$', views.PerfilCliente),
    url(r'^Favoritos/$', views.FavoritosCliente),
    url(r'^Mis-tarjetas/$', views.TarjetasCliente),
    url(r'^Plan-Contratado/(?P<suscripcion_id>[0-9]+)/$',views.PlanContratado),
    url(r'^Plan-Contratado-Diario/(?P<sesiones_id>[0-9]+)/$',views.PlanContratadoDiario),
    url(r'^Suscripciones/$', views.SuscripcionesPerfil),
    url(r'^Calendario/$', views.CalendarioPerfil),
    url(r'^AddTarjetas/$', views.AddTarjetas),
    url(r'^MetodosPagoConekta/$', views.MetodosPagoConekta),
    url(r'^eliminarPagos/$', views.eliminarPagos),
    url(r'^loginCliente/$', views.loginCliente),
    url(r'^LogoutPerfil/$', views.LogoutPerfil),
    url(r'^consultaFacebook/(?P<idFace>\d+)/(?P<email>[^/]+)/(?P<nombre>[A-Za-z]+)/(?P<apellido>[A-Za-z]+)/$', views.consultaFacebook),
    url(r'^consultaGoogle/(?P<idGoogle>\d+)/(?P<email>[^/]+)/(?P<nombre>[A-Za-z]+)/(?P<apellido>[A-Za-z]+)/$', views.consultaGoogle),
    url(r'^EditCliente/$', views.EditCliente),
    url(r'^selectObjetivo/$', views.selectObjetivo),
    url(r'^getFavoritos/(?P<sucursal_id>[0-9]+)/(?P<usuario_id>[0-9]+)/$', views.getFavoritosAdd),
    url(r'^getFavoritosDelete/(?P<sucursal_id>[0-9]+)/(?P<favoritos_id>[0-9]+)/$', views.getFavoritosDelete),
    # Admin
    url(r'^loginAdmin/$', views.loginAdmin),
    url(r'^homeAdmin/$', views.homeAdmin),
    url(r'^homeAdminEstados/$', views.homeAdminEstados),
    url(r'^excel/estados/$', views.ReporteEstados.as_view(),name='Reporte estados'),
    url(r'^addEstado/$', views.addEstado),
    url(r'^editEstado/$', views.editEstado),
    url(r'^deleteEstado/(?P<estado_id>[0-9]+)/$',views.deleteEstado),
    url(r'^homeAdminEstados/(?P<estado_id>[0-9]+)/$', views.homeAdminEstadoCiudades),
    url(r'^excel/estados/(?P<estado_id>[0-9]+)/ciudades/$', views.ReporteEstadoCiudades.as_view(),name='Reporte estado ciudades'),
    url(r'^addCiudad/$', views.addCiudad),
    url(r'^editCiudad/$', views.editCiudad),
    url(r'^deleteCiudad/(?P<ciudad_id>[0-9]+)/$',views.deleteCiudad),
    url(r'^homeAdminServicios/$', views.homeAdminServicios),
    url(r'^excel/servicios/$', views.ReporteServicios.as_view(),name='Reporte servicios'),
    url(r'^addServicio/$', views.addServicio),
    url(r'^editServicio/$', views.editServicio),
    url(r'^deleteServicio/(?P<servicio_id>[0-9]+)/$',views.deleteServicio),
    url(r'^homeAdminActividades/$', views.homeAdminActividades),
    url(r'^excel/actividades/$', views.ReporteActividades.as_view(),name='Reporte actividades'),
    url(r'^addActividad/$', views.addActividad),
    url(r'^editActividad/$', views.editActividad),
    url(r'^deleteActividad/(?P<actividad_id>[0-9]+)/$',views.deleteActividad),
    url(r'^homeAdminClubes/$', views.homeAdminClubes),
    url(r'^excel/clubes/$', views.ReporteClubes.as_view(),name='Reporte clubes'),
    url(r'^addClub/$', views.addClub),
    url(r'^editClubContrasena/$', views.editClubContrasena),
    url(r'^editClub/$', views.editClub),
    url(r'^recortarFotoClub/$', views.recortarFotoClub),
    url(r'^deleteClub/(?P<club_id>[0-9]+)/$',views.deleteClub),
    url(r'^addActividadHorario/$', views.addActividadHorario),
    url(r'^editActividadHorario/$', views.editActividadHorario),
    url(r'^deleteActividadHorario/(?P<actividadHorario_id>[0-9]+)/$',views.deleteActividadHorario),
    url(r'^homeAdminClubes/(?P<club_id>[0-9]+)/Sucursales/$',views.homeAdminClubSucursales),
    url(r'^homeAdminClubesDetallesSucursal/(?P<sucursal_id>[0-9]+)/$',views.homeAdminClubDetallesSucursales),
    url(r'^excel/clubes/(?P<club_id>[0-9]+)/sucursales/$', views.ReporteClubSucursales.as_view(),name='Reporte club sucursales'),
    url(r'^excel/clubes/(?P<club_id>[0-9]+)/sucursales/(?P<sucursal_id>[0-9]+)/servicios/$', views.ReporteSucursalServicios.as_view(),name='Reporte sucursal servicios'),
    url(r'^excel/clubes/(?P<club_id>[0-9]+)/sucursales/(?P<sucursal_id>[0-9]+)/actividades/$', views.ReporteSucursalActividades.as_view(),name='Reporte sucursal actividades'),
    url(r'^excel/clubes/(?P<club_id>[0-9]+)/sucursales/(?P<sucursal_id>[0-9]+)/actividades/(?P<actividad_id>[0-9]+)/horarios/$', views.ReporteSucursalActividadHorarios.as_view(),name='Reporte sucursal actividad horarios'),
    url(r'^excel/clubes/(?P<club_id>[0-9]+)/sucursales/(?P<sucursal_id>[0-9]+)/horario/$', views.ReporteSucursalHorario.as_view(),name='Reporte sucursal horario'),
    url(r'^excel/clubes/(?P<club_id>[0-9]+)/sucursales/(?P<sucursal_id>[0-9]+)/fotos/$', views.ReporteSucursalFotos.as_view(),name='Reporte sucursal fotos'),
    url(r'^excel/clubes/(?P<club_id>[0-9]+)/sucursales/(?P<sucursal_id>[0-9]+)/usuarios/$', views.ReporteSucursalUsuarios.as_view(),name='Reporte sucursal usuarios'),
    url(r'^addSucursal/$', views.addSucursal),
    url(r'^editSucursal/$', views.editSucursal),
    url(r'^editEstatusSucursal/$', views.editEstatusSucursal),
    url(r'^CambiarLogoSucursalAdmin/$', views.CambiarLogoSucursalAdmin),
    url(r'^ServiciosSucursalAdmin/$', views.ServiciosSucursalAdmin),
    url(r'^ActividadesSucursalAdmin/$', views.ActividadesSucursalAdmin),
    url(r'^homeAdminClubes/(?P<club_id>[0-9]+)/Sucursal/(?P<sucursal_id>[0-9]+)/RecortarLogo/$',views.recortarFotoSucursalFormulario),
    url(r'^recortarFotoSucursal/$', views.recortarFotoSucursal),
    url(r'^deleteSucursal/(?P<sucursal_id>[0-9]+)/$',views.deleteSucursal),
    url(r'^addHorarioSucursal/$', views.addHorarioSucursal),
    url(r'^addHorarioMixtoSucursal/$', views.addHorarioMixtoSucursal),
    url(r'^editHorarioSucursal/$', views.editHorarioSucursal),
    url(r'^editHorarioMixtoSucursal/$', views.editHorarioMixtoSucursal),
    url(r'^editRegistroHorario/$', views.editRegistroHorario),
    url(r'^deleteHorarioSucursal/(?P<horario_id>[0-9]+)/$',views.deleteHorarioSucursal),
    url(r'^addFotoSucursal/$', views.addFotoSucursal),
    url(r'^deleteFotoSucursal/(?P<foto_id>[0-9]+)/$',views.deleteFotoSucursal),
    url(r'^homeAdminClubes/(?P<club_id>[0-9]+)/Sucursal/(?P<sucursal_id>[0-9]+)/Usuarios/$',views.sucursalUsuarios),
    url(r'^addUsuario/$', views.addUsuario),
    url(r'^editUsuario/$', views.editUsuario),
    url(r'^deleteUsuario/(?P<usuario_id>[0-9]+)/$',views.deleteUsuario),
    url(r'^homeAdminPagosSucursal/$', views.pagosSucursalAdmin),
    url(r'^homeAdminPagosSucursal/Excel/$', views.ReportePagosSucursal.as_view(),name='Reporte Excel Pagos Sucursal'),
    url(r'^addPagoSucursal/$', views.addPagoSucursal),
    url(r'^deletePagoSucursal/(?P<pago_id>[0-9]+)/$',views.deletePagoSucursal),
    url(r'^homeAdminClientes/$', views.clientesAdmin),
    url(r'^excel/clientes/$', views.ReporteClientes.as_view(),name='Reporte clientes'),
    url(r'^homeAdminReportes/$', views.homeAdminReportes),
    url(r'^filtrarReporte/$', views.filtrarReporteNuevo),
    url(r'^filtrarReporte/sucursal/(?P<sucursal_id>[0-9]+)/subscripciones/inicio=(?P<inicio>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/final=(?P<final>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$',views.filtrarReporteSucursalSubscripciones),
    url(r'^filtrarReporte/excel/sucursal/(?P<sucursal_id>[0-9]+)/subscripciones/inicio=(?P<inicio>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/final=(?P<final>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$',views.ReporteSucursalSubscripciones.as_view(),name='Reporte Subscripciones'),
    url(r'^filtrarReporte/sucursal/(?P<sucursal_id>[0-9]+)/sesiones/inicio=(?P<inicio>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/final=(?P<final>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$',views.filtrarReporteSucursalSesiones),
    url(r'^filtrarReporte/excel/sucursal/(?P<sucursal_id>[0-9]+)/sesiones/inicio=(?P<inicio>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/final=(?P<final>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$',views.ReporteSucursalSesiones.as_view(),name='Reporte Sesiones'),
    url(r'^filtrarReporte/sucursal/(?P<sucursal_id>[0-9]+)/visitas/inicio=(?P<inicio>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/final=(?P<final>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$',views.filtrarReporteSucursalVisitas),
    url(r'^filtrarReporte/excel/sucursal/(?P<sucursal_id>[0-9]+)/visitas/inicio=(?P<inicio>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/final=(?P<final>[0-9]{4}-?[0-9]{2}-?[0-9]{2})/$',views.ReporteSucursalVisitas.as_view(),name='Reporte Visitas'),
    url(r'^logoutAdmin/$',views.logoutAdmin),
    # Club
    url(r'^loginClub/$', views.loginClub),
    url(r'^homeClub/$', views.homeClub),
    url(r'^checkTerminosClub/$',views.checkTerminosClub),
    url(r'^homeClub/Perfil/$', views.clubPerfil),
    url(r'^recortarFotoClub2/$', views.recortarFotoClub2),
    url(r'^editClub2/$', views.editClub2),
    url(r'^homeClub/(?P<club_id>[0-9]+)/Sucursales/$',views.clubSucursales),
    url(r'^addSucursal2/$', views.addSucursal2),
    url(r'^editSucursal2/$', views.editSucursal2),
    url(r'^editEstatusSucursal2/$', views.editEstatusSucursal2),
    url(r'^homeClub/(?P<club_id>[0-9]+)/Sucursal/(?P<sucursal_id>[0-9]+)/RecortarLogo/$',views.recortarFotoSucursalFormulario2),
    url(r'^recortarFotoSucursal2/$', views.recortarFotoSucursal2),
    url(r'^deleteSucursal2/(?P<sucursal_id>[0-9]+)/$',views.deleteSucursal2),
    url(r'^addHorarioSucursal2/$', views.addHorarioSucursal2),
    url(r'^addHorarioMixtoSucursal2/$', views.addHorarioMixtoSucursal2),
    url(r'^editHorarioSucursal2/$', views.editHorarioSucursal2),
    url(r'^editHorarioMixtoSucursal2/$', views.editHorarioMixtoSucursal2),
    url(r'^editRegistroHorario2/$', views.editRegistroHorario2),
    url(r'^deleteHorarioSucursal2/(?P<horario_id>[0-9]+)/$',views.deleteHorarioSucursal2),
    url(r'^addFotoSucursal2/$', views.addFotoSucursal2),
    url(r'^deleteFotoSucursal2/(?P<foto_id>[0-9]+)/$',views.deleteFotoSucursal2),
    url(r'^addActividadHorario2/$', views.addActividadHorario2),
    url(r'^editActividadHorario2/$', views.editActividadHorario2),
    url(r'^deleteActividadHorario2/(?P<actividadHorario_id>[0-9]+)/$',views.deleteActividadHorario2),
    url(r'^homeClub/(?P<club_id>[0-9]+)/Sucursal/(?P<sucursal_id>[0-9]+)/Usuarios/$',views.sucursalUsuarios2),
    url(r'^addUsuario2/$', views.addUsuario2),
    url(r'^editUsuario2/$', views.editUsuario2),
    url(r'^deleteUsuario2/(?P<usuario_id>[0-9]+)/$',views.deleteUsuario2),
    url(r'^homeClub/Reservaciones/$', views.reservacionesClub),
    url(r'^homeClub/Pagos/$', views.pagosClub),
    url(r'^logoutClub/$',views.logoutClub),
    # Sucursal
    url(r'^loginSucursal/$', views.loginSucursal),
    url(r'^homeSucursal/$', views.homeSucursal),
    url(r'^checkTerminosSucursal/$',views.checkTerminosSucursal),
    url(r'^homeSucursal/Perfil/$', views.sucursalPerfil),
    url(r'^editSucursal3/$', views.editSucursal3),
    url(r'^homeSucursal/RecortarLogo/$',views.recortarFotoSucursalFormulario3),
    url(r'^recortarFotoSucursal3/$', views.recortarFotoSucursal3),
    url(r'^addHorarioSucursal3/$', views.addHorarioSucursal3),
    url(r'^addHorarioMixtoSucursal3/$', views.addHorarioMixtoSucursal3),
    url(r'^editHorarioSucursal3/$', views.editHorarioSucursal3),
    url(r'^editHorarioMixtoSucursal3/$', views.editHorarioMixtoSucursal3),
    url(r'^editRegistroHorario3/$', views.editRegistroHorario3),
    url(r'^deleteHorarioSucursal3/(?P<horario_id>[0-9]+)/$',views.deleteHorarioSucursal3),
    url(r'^addFotoSucursal3/$', views.addFotoSucursal3),
    url(r'^deleteFotoSucursal3/(?P<foto_id>[0-9]+)/$',views.deleteFotoSucursal3),
    url(r'^addActividadHorario3/$', views.addActividadHorario3),
    url(r'^editActividadHorario3/$', views.editActividadHorario3),
    url(r'^deleteActividadHorario3/(?P<actividadHorario_id>[0-9]+)/$',views.deleteActividadHorario3),
    url(r'^homeSucursal/Clientes/$', views.sucursalClientes),
    url(r'^homeSucursal/Cliente/(?P<cliente_id>[0-9]+)/Notificacion/$',views.notificacionCliente),
    url(r'^homeSucursal/Cliente/(?P<cliente_id>[0-9]+)/HistorialVisitas/$',views.clienteHistorialVisitas),
    url(r'^registrarVisitaSub/(?P<cliente_id>[0-9]+)/$',views.registrarVisitaSub),
    url(r'^registrarVisitaSes/(?P<cliente_id>[0-9]+)/$',views.registrarVisitaSes),
    url(r'^homeSucursal/Visitas/$', views.sucursalVisitas),
    url(r'^homeSucursal/Pagos/$', views.pagosSucursal),
    url(r'^logoutSucursal/$',views.logoutSucursal),
    # Busquedas AJAX
    url(r'^getCiudades/(?P<estado_id>\d+)/$', views.getCiudades, name='getCiudades'),
    # Login y Logout user API
    url(r'^userLogin/$',views.UserLoginAPIView.as_view(),name='login'),
    url(r'^userLogout/$',views.UserLogoutAPIView.as_view(),name='logout'),
    # API's personalizadas
    url(r'actualizarFotoCliente/$',views.ActualizarFotoClienteAPIView.as_view(),name="actualizar foto de perfil"),
    url(r'calcularPromedioEvaluaciones/$',views.CalcularPromedioEvaluacionesAPIView.as_view(),name="calcular promedio de evaluaciones"),
    # Conekta API
    url(r'^addCustomerConekta/$', CustomerConektaApiView.as_view(),name="Agregar customer Conekta"),
    url(r'^deleteCustomerConekta/$', BorrarCustomerConektaApiView.as_view(),name="Borrar customer Conekta"),
    url(r'^metodosPagoConekta/$', MetodosPagoApiView.as_view(),name="Metodos de pago Conekta"),
    url(r'^addMetodoPagoConekta/$', AddMetodoPagoApiView.as_view(),name="Agregrar metodo de pago Conekta"),
    url(r'^deleteMetodoPagoConekta/$', deleteMetodoPagoApiView.as_view(),name="Borrar metodo de pago Conekta"),
    url(r'^SubscripcionMensual/$', SubscripcionMensualApiView.as_view(),name="Subscripcion mensual"),
    url(r'^CancelarSubscripcionMensual/$', CancelarSubscripcionMensualApiView.as_view(),name="Cancelar subscripcion mensual"),
    url(r'^ActualizarSubscripcionMensual/$', ActualizarSubscripcionMensualApiView.as_view(),name="Actualizar subscripcion mensual"),
    url(r'^CobrarPorSesion/$', CobrarPorSesionApiView.as_view(),name="Cobrar por sesion"),
    # Consulta fecha
    url(r'^consultarFecha/$', ConsultaFechaAPIView.as_view(),name="Consultar Fecha"),
    # Consultar perfil sucursal
    url(r'^perfilSucursal/$', PerfilSucursalAPIView.as_view(),name="Perfil Sucursal"),
    # Consultar dias disponibles
    url(r'^diasDisponibles/$', DiasDisponiblesAPIView.as_view(),name="Dias Disponibles"),
    # Restablecer contrasena
    url(r'^RestaurarContrasena/$', views.RecuperarContrasena),
    url(r'^recuperarContrasenaPte1/$', views.recuperarContrasenaPte1),
    url(r'^RecuperarContrasena/incidencia=(?P<idIncidencia>[0-9]+)/$',views.FormularioPassword),
    url(r'^recuperarContrasenaPte2/$', views.recuperarContrasenaPte2),
    url(r'RevisarVisita/$',views.RevisarVisitaAPIView.as_view(),name="Revisar visita"),
    url(r'RegistrarVisita/$',views.RegistrarVisitaAPIView.as_view(),name="Registrar visita"),
    url(r'RevisarSubscripcionFree/$',views.RevisarSubscripcionFreeAPIView.as_view(),name="Revisar Subscripcion Free"),
    url(r'ActivarSubscripcionFree/$',views.ActivarSubscripcionFreeAPIView.as_view(),name="Activar Subscripcion Free"),
    url(r'RegistrarCelular/$',views.RegistrarCelularAPIView.as_view(),name="Registrar celular"),
    url(r'CheckPhone/$',views.CheckPhoneAPIView.as_view(),name="Check phone"),
    url(r'UpdatePhone/$',views.UpdatePhoneAPIView.as_view(),name="Update phone"),
    url(r'VerifyPhone/$',views.VerifyPhoneAPIView.as_view(),name="Verify phone"),
    url(r'GetSubscriptions/$',views.GetSubscriptionsAPIView.as_view()),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)